### ISSUE TITLE
JC IS GOD

### ISSUE THREAD

**Issue by cryptomaniac79** [seatrips/Tools#1]
Repo URL: https://github.com/GOD
Title of the tool: GOD
Repo owner: GOD
Slack ID: @heaven

**Comment by seatrips** [comment]
Thks for your Sick Repo GOD

**Comment by jamiec79** [comment]
mofo

**Comment by cryptomaniac79** [comment]
from G.O.D

**Comment by cryptomaniac79** [comment]
whhhhhhhy no repo...

**Comment by jamiec79** [comment]
wen repo

**Comment by seatrips** [comment]
J.E.Z.U.S Loves YOU

**Comment by jamiec79** [comment]
mofffoooooo

God is pissed

**Comment by seatrips** [comment]
well https://en.wikipedia.org/wiki/Adult_diaper
